### ISSUE TITLE
Exception Handling in map

### ISSUE THREAD

**Issue by martinei** [lambdista/try#11]
The current implementation of map takes a Function:
```
        @Override
        public <U> Try<U> map(Function<? super T, ? extends U> mapper) {
            return Try.apply(() -> mapper.apply(value));
        }

```  
This means map can not do Exception Handling for checked Exceptions:

```
 public String throwingAnException() throws IOException {
    return "foo";
  }
  
  public void testMap() {
    Try<String> myTry = Try.apply(() ->  "start");
    myTry.map(this::throwingAnException);
//                       ^^ Unhandled Exception IOException
}  

```

If you'd use "FailableFunction" similair to the FailableSupplier in this Project it would increase the usability of Try.

**Comment by lambdista** [comment]
With this API you already have the *failable* function concept. If you think about it, a failable function is something like:
```
Function<? super T, ? extends Try<U>>
```
That is a function that goes from `T` to `Try<U>`, that is it may fail. 

Note that you already have a combinator for such a function and its name is `flatMap`. Here's its signature:
```
public abstract <U> Try<U> flatMap(Function<? super T, ? extends Try<U>> mapper);
```
You should rewrite your `testMap` this way:
```
public void testMap() {
    Try<String> myTry = Try.apply(() -> "start");

    myTry.flatMap(s -> Try.apply(this::throwingAnException));
}
```

**Comment by martinei** [comment]
Thanks for your reply. While I understand that a ` Function<? super T, ? extends Try<U>>` can be seen as implementation of the concept of a _failable_ function I believe there is a huge difference in the usability. My example contained a Checked Exception.  For  unchecked exceptoin a innocent looking:
`someTry.map(someBadFunction())](url)`
can throw unexpected Exceptions as well as a 
`someTry.flatMap(someOtherBadFunction())](url)`
I beliebe this comes as a surprise to the reader/writer as the idea of Try is to map Exceptions to explicit values/types. It basically means you have to guard any usage of map and flatMap with another Try which is quite ugly. 
By comparison Scalas Try catches Exceptions within both map and flatMap (https://github.com/scala/scala/blob/v2.9.3-RC1/src/library/scala/util/Try.scala#L205,https://github.com/scala/scala/blob/v2.9.3-RC1/src/library/scala/util/Try.scala#L198)

**Comment by lambdista** [comment]
Could you, please, provide an example of using `map` and `flatMap` where the functions they use throw an unchecked exception and this library don't trap it within a `Try`? Have a look at this:
```
public class MapAndFlatMapExample {
    static String throwingAnException() throws IOException {
        return "foo";
    }

    static void workingWithCheckedEx() {
        Try<String> myTry = Try.apply(() -> "start");

        Try<String> result = myTry.flatMap(s -> Try.apply(MapAndFlatMapExample::throwingAnException));

        result.forEach(System.out::println);
    }

    static String throwingUncheckedExWithinMap(String s) {
        throw new IllegalStateException("ops!");
    }

    static Try<String> throwingUncheckedExWithinFlatMap(String s) {
        throw new IllegalStateException("ops!");
    }

    static void workingWithUncheckedEx() {
        Try<String> myTry = Try.apply(() -> "start");

        Try<String> result = myTry.map(MapAndFlatMapExample::throwingUncheckedExWithinMap);

        Try<String> result2 = myTry.flatMap(MapAndFlatMapExample::throwingUncheckedExWithinFlatMap);

        result.forEach(System.out::println);

        result2.forEach(System.out::println);
    }

    public static void main(String[] args) {
        workingWithCheckedEx();

        workingWithUncheckedEx();
    }
}
```

**Comment by martinei** [comment]
You are absolutely right. It just works for Unchecked Exceptions and making the try explicit for checked exceptions is also fine. Many thanks for your patience and sorry for the noise.

**Comment by lambdista** [comment]
You're more than welcome. Thank you for using this library.
